[package]
name = "rjvm_reader"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.64"
bitflags = "2.6.0"
strum_macros = "0.26.4"
result = "1.0.0"
log = "0.4.22"
test-log = "0.2.16"
env_logger = "*"
itertools = "0.13.0"
cesu8 = "1.1.0"
